//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Afonichev.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityJury
    {
        public int Id { get; set; }
        public int ActivityId { get; set; }
        public int JuryId { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Member Member { get; set; }
    }
}
