//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Afonichev.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.ActivityJury = new HashSet<ActivityJury>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Day { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public int ModerateId { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual ICollection<ActivityJury> ActivityJury { get; set; }
    }
}
