//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Afonichev.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Activity = new HashSet<Activity>();
            this.ActivityJury = new HashSet<ActivityJury>();
            this.Event = new HashSet<Event>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public int CityId { get; set; }
        public string Phone { get; set; }
        public Nullable<int> EventId { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
        public int GenderId { get; set; }
        public int RoleId { get; set; }
    
        public virtual ICollection<Activity> Activity { get; set; }
        public virtual ICollection<ActivityJury> ActivityJury { get; set; }
        public virtual ICollection<Event> Event { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Role Role { get; set; }
    }
}
